---
apiVersion: v1
kind: Namespace
metadata:
  name: kosli

---
apiVersion: v1
kind: Service
metadata:
  name: hello-kosli
  namespace: kosli
  labels:
    app: hello-kosli
spec:
  type: NodePort
  selector:
    app: hello-kosli
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kosli
  namespace: kosli
  labels:
    app: hello-kosli
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-kosli
  template:
    metadata:
      labels:
        app: hello-kosli
    spec:
      containers:
      - name: hello-kosli
        image: ghcr.io/dangrondahl/hello-kosli:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /version
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /version
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
