name: CI

on:
  pull_request:
    branches:
      - main

env:
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  KOSLI_ORG: "dangrondahl"
  KOSLI_FLOW: "hello-kosli"

jobs:
  create-flow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup kosli
        uses: kosli-dev/setup-cli-action@v2

      - name: Create Kosli Flow
        run: |
          kosli create flow $KOSLI_FLOW \
            --description "A simple Go web server that integrates with Kosli" \
            --org $KOSLI_ORG

      - name: Attest pull-request evidence to Kosli
        run:
          kosli attest pullrequest github
            --github-token="${{ secrets.GITHUB_TOKEN }}"
            --name=pull-request
