name: CI

on:
  pull_request:
    branches:
      - main

env:
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  KOSLI_ORG: "dangrondahl"
  KOSLI_FLOW: "hello-kosli"
  REGISTRY: ghcr.io/dangrondahl
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: setup kosli
        uses: kosli-dev/setup-cli-action@v2

      - name: Create Kosli Flow
        run: |
          kosli create flow $KOSLI_FLOW \
            --description "A simple Go web server that integrates with Kosli" \
            --org $KOSLI_ORG \
            --template-file .kosli/template.yml

      - name: Begin Kosli Trail
        run: |
          kosli begin trail "${GITHUB_SHA}" \
            --description="CI run for build: ${GITHUB_RUN_NUMBER} on ref: ${GITHUB_REF_NAME}"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Run tests with coverage
        id: coverage
        run: |
          make coverage

      #- name: Attest test coverage to Kosli
      #  run: |
      #    kosli attest custom \
      #      --type goCoverage \
      #      --name yourTemplateArtifactName.yourAttestationName \
      #      --attestation-data coverage/coverage.json \
      #      --commit "${GITHUB_SHA}"

      - name: Build Docker image
        id: build-docker
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: false
          build-args: |
            GIT_SHA=${{ github.sha }}
